apiVersion: v1
kind: Service
metadata:
  name: hogwarts-admission-svc
spec:
  selector:
    app: hogwarts-admission
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8084
  type: NodePort